dist: xenial
language: python
python:
  - "3.8"
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - flake8
  - mypy decision_engine/*.py
  - coverage run --include=decision_engine/* --omit=tests/* -m pytest
  - coverage xml
  - python-codacy-coverage -r coverage.xml
after_success:
  - codecov
