dist: xenial
language: python
python:
  - "3.8"
env:
  global:
    - CC_TEST_REPORTER_ID=fb1273a6f13d10a9564769d6f1f04fdbc8e28630be4357da4ce31ecb3aa9810c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - pip install pipenv scrutinizer-ocular
install:
  - pipenv install --dev
script:
  - flake8
  - mypy --ignore-missing-imports decision_engine/*.py
  - coverage run --include=decision_engine/* --omit=tests/* -m pytest
  - coverage xml
  - python-codacy-coverage -r coverage.xml
after_script:
  - ocular
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
